nama = str(input("Masukan nama : "))
umur = int(input("Masukan umur : "))
pekerjaan_ortu = str(input("Masukan Pekerjaan orang tua dengan menggunakan huruf besar (PEDAGANG,KOKI) : ")) 
gaji_ortu = int(input("Masukan Gaji perbulan : "))
ipk = float(input('Masukan IPK dengan nilai desimal seperti (3.5) : '))
blacklist_kerja = ['PNS','GURU','DOKTER','TENTARA','DOSEN','PRESIDEN','GUBERNUR','WALIKOTA']


if (pekerjaan_ortu not in blacklist_kerja and gaji_ortu <= 1000000 and umur<25 and ipk>=2.8):
    print('~~~'*20)
    print('~~~'*20)
    print(f'Nama : {nama}')
    print(f'Umur : {umur}')
    print(f'Pekerjaan Orang tua : {pekerjaan_ortu}')
    print(f'Gaji/Bulan Orang tua : {gaji_ortu:,}')
    print(f'IPK : {ipk}')
    print('')
    print('')
    print(f'SELAMAT ANDA MEMENUHI SYARAT UNTUK MENDAPATKAN BEASISWA MERDEKA BELAJAR !!!! ')
    print('~~~'*20)
    print('~~~'*20)                
else:
    print('~~~'*20)
    print('~~~'*20)
    print(f'Nama : {nama}')
    print(f'Umur : {umur}')
    print(f'Pekerjaan Orang tua : {pekerjaan_ortu}')
    print(f'Gaji/Bulan Orang tua : {gaji_ortu:,}')
    print(f'IPK : {ipk}')
    print('')
    print('')
    print(f'MOHON MAAF DOKUMEN YANG ANDA KIRIM TIDAK MEMENUHI PERSYARATAN ')
    print('~~~'*20)
    print('~~~'*20)